-- DS Automobiles — Modo Silêncio
-- Schema Supabase / PostgreSQL para tabela de leads

CREATE TABLE IF NOT EXISTS public.ds_silencio_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_record_id VARCHAR(64) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    telefone VARCHAR(30) NOT NULL,
    codigo_postal VARCHAR(12) NOT NULL,
    confirmacao_dados BOOLEAN NOT NULL DEFAULT TRUE,
    marcar_test_drive BOOLEAN NOT NULL DEFAULT FALSE,
    submitted_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT uq_ds_silencio_client_record_id UNIQUE (client_record_id)
);

-- Índices para pesquisa, ordenação e relatórios
CREATE INDEX IF NOT EXISTS idx_ds_leads_received_at ON public.ds_silencio_leads (received_at DESC);
CREATE INDEX IF NOT EXISTS idx_ds_leads_test_drive ON public.ds_silencio_leads (marcar_test_drive);
CREATE INDEX IF NOT EXISTS idx_ds_leads_email ON public.ds_silencio_leads (email);

-- Configuração de Segurança (Row Level Security - RGPD)
ALTER TABLE public.ds_silencio_leads ENABLE ROW LEVEL SECURITY;

-- 1. Permitir inserção de leads (necessário para a API pública ou chave anon/service_role)
DROP POLICY IF EXISTS "Permitir inserção de leads" ON public.ds_silencio_leads;
CREATE POLICY "Permitir inserção de leads" 
    ON public.ds_silencio_leads 
    FOR INSERT 
    TO anon, authenticated, service_role 
    WITH CHECK (true);

-- 2. Restringir leitura: apenas administradores autenticados ou service_role podem consultar os dados
DROP POLICY IF EXISTS "Permitir leitura apenas por administradores" ON public.ds_silencio_leads;
CREATE POLICY "Permitir leitura apenas por administradores" 
    ON public.ds_silencio_leads 
    FOR SELECT 
    TO authenticated, service_role 
    USING (true);
